Pin a buggy elasticsearch python dependency
Python elasticsearch package >=7.15 was causing a bug during documents
export:

TypeError: search() got multiple values for keyword argument 'size'